"""empty message

Revision ID: 1c5c440d19ec
Revises: bb057471f6d2
Create Date: 2016-02-06 21:49:26.049293

"""

# revision identifiers, used by Alembic.
revision = '1c5c440d19ec'
down_revision = 'bb057471f6d2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('data', 'date_log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('date_log', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('data', 'timestamp')
    ### end Alembic commands ###
