"""empty message

Revision ID: 8faf82f39090
Revises: 1c5c440d19ec
Create Date: 2016-02-06 21:54:46.383402

"""

# revision identifiers, used by Alembic.
revision = '8faf82f39090'
down_revision = '1c5c440d19ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'arduino', sa.Column('laboratory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'arduino', 'laboratory', ['laboratory_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arduino', type_='foreignkey')
    op.drop_column(u'arduino', 'laboratory_id')
    op.drop_table('laboratory')
    ### end Alembic commands ###
