"""empty message

Revision ID: bb057471f6d2
Revises: 98208e17c348
Create Date: 2016-02-06 18:56:10.642633

"""

# revision identifiers, used by Alembic.
revision = 'bb057471f6d2'
down_revision = '98208e17c348'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arduino', sa.Column('secret_key', sa.String(length=16), nullable=False))
    op.create_unique_constraint(None, 'arduino', ['secret_key'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arduino', type_='unique')
    op.drop_column('arduino', 'secret_key')
    ### end Alembic commands ###
